name: Purge jsDelivr Cache

on:
  push:
    branches: [ main ]
    # Optional: only run when these folders change
    paths:
      - 'packages/**'
      - 'scripts/**'
      - '.github/workflows/purge-jsdelivr.yml'

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Build list of files to purge
        id: files
        run: |
          FILES=()
          # ====== LIST EVERY ASSET YOUR WEBFLOW LINKS USE ======
          FILES+=("https://purge.jsdelivr.net/gh/SweQuant/site@main/packages/vars-anchor.css")
          FILES+=("https://purge.jsdelivr.net/gh/SweQuant/site@main/packages/nav.css")
          FILES+=("https://purge.jsdelivr.net/gh/SweQuant/site@main/packages/cad-grid.css")
          FILES+=("https://purge.jsdelivr.net/gh/SweQuant/site@main/packages/bg-nonlinear.css")
          FILES+=("https://purge.jsdelivr.net/gh/SweQuant/site@main/packages/reveal.css")
          FILES+=("https://purge.jsdelivr.net/gh/SweQuant/site@main/packages/wipe-heading.css")
          FILES+=("https://purge.jsdelivr.net/gh/SweQuant/site@main/packages/button-eclipse.css")

          # If you also host JS, add them here the same way:
          # FILES+=("https://purge.jsdelivr.net/gh/SweQuant/site@main/scripts/whatever.js")

          printf "%s\n" "${FILES[@]}" > urls.txt
          echo "count=$(wc -l < urls.txt)" >> $GITHUB_OUTPUT

      - name: Purge each file
        run: |
          while read -r URL; do
            echo "Purging: $URL"
            # Add a tiny delay to be polite
            curl -fsS -X GET "$URL" || true
            sleep 0.4
          done < urls.txt

      - name: Summary
        run: echo "Purged $(wc -l < urls.txt) url(s)."
